highlighter: pygments
github: https://github.com/RafaAguilar/RafaAguilar.github.io.git

# Site settings
title: Blog de Rafa Aguilar
email: rafael.aguilar.1987@gmail.om
description: > # this means to ignore newlines until "baseurl:"
  Un blog sobre Informática, Arte y Ciencia en General
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://RafaAguilar.github.io" # the base hostname & protocol for your site
twitter_username: RafaAguilar1987
github_username:  RafaAguilar

# Build settings
markdown: kramdown

